### PR TITLE
Adding english section documents

### PR DESCRIPTION
**Pull request by jvanulde**

### CODE REVIEW

**Comment by jvanulde** [comment]
@anthonyfok does the approach of section documents in a language folder make sense?

**Review by anthonyfok — CHANGES_REQUESTED** [review]
Hi @jvanulde, thank you for creating the skeleton section documents.  I like how you have set `en` and `fr` as subdirectories for different language versions of the paper.

There is something that I recommend changing though.  `.ascii` does not seem to be a common file extension for AsciiDoc.  According to https://asciidoctor.org/docs/asciidoc-recommended-practices/#document-extension:

> AsciiDoc doesn’t care which extension you use. GitHub supports the extensions `.asciidoc`, `.adoc` and `.asc`.
>
> `.adoc` seems to be the most often used extension and the one we prefer. It does not conflict with other well known applications, is distinct, and not excessively long (like `.asciidoc`). It also reads as “a doc”. Our recommendation, therefore, is to use `.adoc`.
>
> > We strongly recommend against using the `.asc` extension. The connection to AsciiDoc isn’t immediately obvious and it gets falsely identified as a PGP file on Linux.

So, yes, it would be great if you could rename all the *.ascii files to *.adoc, and then this PR would be good to merge!  Thank you!

**Comment by anthonyfok** [comment]
> @anthonyfok does the approach of section documents in a language folder make sense?

@jvanulde Yes!  This is a great idea, and something that had totally escaped my mind because I forgot the fact that our Pathways paper will eventually be translated into French too.  😅  Yes, I think language folders like `en` and `fr` make total sense.

**Comment by jvanulde** [comment]
Thanks @anthonyfok for catching the file extension error. I have fixed them and committed to the branch. Should be in the PR now.

**Review by anthonyfok — APPROVED** [review]
Thank you @jvanulde!  Looks great to me!

**Pull request merged**
